version: "3.9"

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        container_name: database
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    api:
        build: 
            context: ./api
        working_dir: /app
        ports:
            - "3000:3000"
        # command: |
        #     npx sequelize-cli db:create
        volumes:
            - .:/code
            - logvolume01:/var/log
        depends_on:
            - postgres
        container_name: api
        # restart: always

volumes:
    logvolume01: {}

