version: '3.1'

services:
  development_database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: alerki_dev
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/dev:/var/lib/postgresql/data
  testing_database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: alerki_test
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres/test:/var/lib/postgresql/data
