version: "3.9"

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USERNAME=root
        container_name: database

    api:
        build: 
            context: ./api/
        working_dir: /app
        ports:
            - "3000:3000"
        volumes:
            - .:/code
            - logvolume01:/var/log
        depends_on:
            - postgres
        container_name: api
        restart: always

volumes:
    logvolume01: {}

