version: '3.1'

services:
  cache:
    image: redis:6
    container_name: cache
    ports:
      - '6379:6379'
  alerki_directus:
    image: directus/directus:10.10.4
    container_name: alerki_directus
    ports:
      - 8055:8055
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: 'development_database'
      DB_PORT: '5432'
      DB_DATABASE: 'alerki_dev'
      DB_USER: 'root'
      DB_PASSWORD: 1234
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
      ADMIN_EMAIL: 'root@gmail.com'
      ADMIN_PASSWORD: 'root'
    depends_on:
      - cache
      - development_database
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
  development_database:
    image: postgres
    container_name: development_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: alerki_dev
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/dev:/var/lib/postgresql/data
  testing_database:
    image: postgres
    container_name: testing_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: alerki_test
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres/test:/var/lib/postgresql/data
