version: "3.9"

services:
    db:
        container_name: database
        environment:
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_DATABASE
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ../pgdata/production:/var/lib/postgresql/data

    backend:
        build: 
            context: ../api/
            dockerfile: Dockerfile
        container_name: api
        command: bash -c "npm run migrate && npm run start"
        depends_on:
            - db
        env_file: .env.production
        ports:
            - "3001:3001"
        working_dir: /app/api


    frontnend:
        build:
            context: ../frontend/
            dockerfile: Dockerfile
        container_name: frontend
        command: bash -c "npm run build && npm run start"
        depends_on:
            - backend
        ports:
            - "3000:3000"
        volumes:
            - ../:/app
        working_dir: /app/frontend
