version: "3.9"

services:
  postgres:
    container_name: postgres-dev
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: appointment_dev
    ports:
      - 5551:5432
