version: "3.9"

services:
  postgres:
    container_name: postgres-test
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: appointment_test
    ports:
      - 5552:5432
