name: Build and push Docker images

on:
  pull_request:
    branches:
      - prod

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      - uses: actions/checkout@v2

      - name: Wait for testing and linting
        uses: Sasha-hk/Alerki/.github/workflows/ci.yml

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./frontend
          push: true
          tags: Sasha-hk/alerki-frontend:latest
          secrets: |
              GIT_AUTH_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }}
