name: CI

on:
  push:
    branches:
      - main
      - '!prod'

  pull_request:

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install packages
        run: yarn install

      - name: Lint code
        run: yarn run lint

  api-testing:
    name: Unit and integration testing
    needs: lint-code
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: appointment_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5552:5432

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Unit testing with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: Change directory to api
      run: cd api

    - name: Install packages
      run: yarn install

    - name: Test the code
      run: |
        cd api
        yarn run test
