name: "CI"

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lint

  api-test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: alerki_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5552:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Ent to end testing
        run: |
          cd api
          yarn test:e2e
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
