name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # lint-code:
  #   name: Lint code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #         cache: yarn

  #     - name: Install packages
  #       run: yarn install

  #     - name: Lint code
  #       run: yarn run lint

  api-testing:
    name: Unit and integration testing
    # needs: lint-code
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: appointment_test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5552:5432

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: yarn test:e2e
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
