name: Demo Push

on:
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: -img

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker-compose up --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
