name: Build

on:   
  push:
    branches:
      - main

    paths-ignore:
      - 'documentation/**'
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

  pull_request:
    branches:
      - main

    paths-ignore:
      - 'documentation/**'
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: . ./docker/build-production.sh
