name: Node.js CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install packages
        run: |
          yarn install
          cd api
          yarn install

      - name: Lint code
        run: |
          yarn lint

  unit-testing:
    name: Unit testing
    needs: lint-code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Unit testing with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install
    - run: cd api && yarn test:unit
