name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint code
        run: |
          yarn install
          yarn lint

  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          yarn install

      - name: Lint code
        run: |
          . ./docker/build-test.sh

  integration-testing:
    name: Integration testing
    runs-on: ubuntu-latest
    needs: lint-code
    steps:
      - uses: actions/checkout@v2

      - name: Test API
        run: |
          docker-compose -f ./docker/docker-compose.test.yml up --exit-code-from backend
