name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          . ./docker/build-test.sh

  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint code
        run: |
          yarn lint

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint code
        run: |
          docker-compose -f ./docker/docker-compose.test.yml up --exit-code-from backend
